#cloud-config
# TODO:
# - init script once
#   - create user
#   - create API token
# - run script
# - install plugins (iterate json file remotely)

package_upgrade: true
runcmd:
  - wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
  - apt-add-repository "deb https://pkg.jenkins.io/debian-stable binary/"
  - apt-get update && apt-get install jenkins docker.io openjdk-8-jre -y
  - echo 'JAVA_ARGS="-Djenkins.install.runSetupWizard=false"' >> /etc/default/jenkins
  - usermod -aG docker jenkins
  - mkdir -p /var/lib/jenkins/init.groovy.d
  - curl https://raw.githubusercontent.com/john-ho-codeonit-com/jenkins-vm/master/0-init-user.groovy -o /var/lib/jenkins/init.groovy.d/0-init-user.groovy
  - curl https://raw.githubusercontent.com/john-ho-codeonit-com/jenkins-vm/master/1-init-plugins.groovy -o /var/lib/jenkins/init.groovy.d/1-init-plugins.groovy
  - curl https://raw.githubusercontent.com/john-ho-codeonit-com/jenkins-vm/master/2-init-token.groovy -o /var/lib/jenkins/init.groovy.d/2-init.groovy
  - service jenkins restart